### ISSUE TITLE
Launch notebook on JupyterHub

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/globe-experiment-finder#10]
Use JupyterHub REST API https://jupyterhub.readthedocs.io/en/latest/reference/rest.html
Required for #6

**Comment by bpmweel** [comment]
Nice to have:

Dropdown menu with standard experiments to generate.

**Comment by sverhoeven** [comment]
The experiment is a notebook located in a experiment directory which is in the users home dir.
The url the launcher returns should open the notebook.

**Comment by bpmweel** [comment]
Current system design: https://www.draw.io/#G1UHls1j-cjB8YXUvSjXDzQPIHD55q0ERk
